[package]
name = "ferium"
version = "3.22.1"
edition = "2021"
authors = ["Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>", "Daniel Hauck (SolidTux)"]
description = "Ferium is a CLI program for managing Minecraft mods from Modrinth, CurseForge, and Github Releases"
exclude = ["tests"] # Don't need tests for installing using crates.io
repository = "https://github.com/theRookieCoder/ferium"
categories = ["command-line-utilities"]
readme = "README.md"
license = "MPL-2.0"
keywords = [
    "minecraft",
    "mod-manager",
    "modrinth",
    "curseforge",
    "github"
]

[features]
default = ["gui"]
gui = ["libium/gui"]

[dependencies]
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0", default-features = false, features = ["rustls-tls"] }
octocrab = { version = "0", default-features = false, features = ["rustls"] }
clap = { version = "3", features = ["derive"] }
lazy_static = "1"
serde_json = "1"
dialoguer = "0"
itertools = "0"
colored = "2"
ferinth = "2"
anyhow = "1"
libium = "1"
online = "3"
semver = "1"
furse = "1"
bytes = "1"
url = "2"

[dev-dependencies]
rand = "0"
