name: Build and Release

on:
  push:
    # tags:
    #   - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: sudo apt-get install librust-gdk-dev
      - name: Lint code
        run: just lint
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
  build-linux:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: sudo apt-get install librust-gdk-dev
      - name: Build
        run: just build-linux
      - run: ls out
  build-mac:
    runs-on: macos-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: just build-mac
      - run: ls out
  build-win:
    runs-on: windows-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: just build-win
      - run: ls out
