name: Build and Release

on:
  push:
    # tags:
    #   - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
      - name: Install dependencies
        run: sudo apt-get install librust-gdk-dev
      - name: Lint code
        run: just lint
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  build-linux:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
          target: x86_64-unknown-linux-gnu
      - name: Install dependencies
        run: sudo apt-get install librust-gdk-dev
      - name: Build
        run: just build-linux
      - run: ls out

  build-mac:
    runs-on: macos-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-darwin
          target: aarch64-apple-darwin
      - name: Build
        run: just build-mac
      - run: ls out

  build-win:
    runs-on: windows-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
      - name: Build
        run: just build-win
      - run: ls out
