name: Build and Release

on:
  push:
    # tags:
    #   - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: sudo apt-get install librust-gdk-dev
      - name: Lint code
        run: just lint
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
