name: Build and Release

# Only run when a tag is pushed
on:
  push:
    branches: [aur_action]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1

      - name: Install Rust for macOS
        if: matrix.os == 'macos-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - name: Install Rust for Windows
        if: matrix.os == 'windows-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Rust for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install librust-gdk-dev gcc-mingw-w64-x86-64

      - name: Lint code
        run: just lint

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: just build-mac
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: just build-win
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: just build-linux
      - name: Build Linux NoGUI
        if: matrix.os == 'ubuntu-latest'
        run: just build-linux-nogui

      - name: Upload build artefacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: out/ferium*.zip
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./out
      - name: Download ferium from AUR
        run: git clone ssh://aur@aur.archlinux.org/ferium-bin.git
      - name: Upgrade PKGBUILD
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: ./ferium-bin/
          pkgver: '${{ github.ref_name }}'
          updpkgsums: true
          srcinfo: true
          flags: ''
      - name: Upload to the AUR
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -v -t ssh-rsa aur.archlinux.org >>~/.ssh/known_hosts
          echo "Host aur.archlinux.org" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/aur" >> ~/.ssh/config
          echo "  User aur" >> ~/.ssh/config
          echo "${{ secrets.PRIVATE }}" >> ~/.ssh/aur
          chmod -vR 600 ~/.ssh/aur
          ssh-keygen -vy -f ~/.ssh/aur >~/.ssh/aur.pub
          cd ferium-bin
          git config --global user.email "shiue.kyle@gmail.com"
          git config --global user.name "KyleUltimate"
          git add .
          git commit -m "Auto update to ${{ github.ref_name }}"
          git remote add aur "ssh://aur@aur.archlinux.org/ferium-bin"
          git push origin master

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/*
          name: Ferium ${{ github.ref_name }}
          body: |
            Compiled binaries for Ferium version `${{ github.ref_name }}` ([changelog](https://github.com/theRookieCoder/ferium/blob/main/CHANGELOG.md#${{ github.ref_name }}))

            The provided binaries are for:

            - GNU Linux (x64 linux gnu) without a GUI file dialog and libraries
            - GNU Linux (x64 linux gnu)
            - macOS Apple Silicon (aarch64 darwin)
            - macOS Intel (x64 darwin)
            - GNU Windows, e.g. cygwin (x64 windows gnu)
            - MSVC Windows (x64 windows msvc)

            You can install these by downloading and unzipping the appropriate asset, and moving the executable to ~/bin or any other binary folder in your path.
